name: "Private Action"
description: "A reusable private action that can process input or download artifacts"
author: "Your Name"
runs:
  using: "composite"
  steps:
    # Step 1: Echo input
    - name: Print input
      shell: bash
      run: |
        echo "Received input_message: ${{ inputs.input_message }}"

    # Step 2: Optionally download artifact
    - name: Download artifact
      if: ${{ inputs.artifact_name != '' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}

inputs:
  input_message:
    description: "A message passed from the calling workflow"
    required: true
  artifact_name:
    description: "Name of the artifact to download (optional)"
    required: false
    default: ""